//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDiarySystem.Resources.Schedule.Update {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UpdateTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdateTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchoolDiarySystem.Resources.Schedule.Update.UpdateTexts", typeof(UpdateTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables us to update a student&apos;s data with its relevant data: class, subject, time and day..
        /// </summary>
        public static string ScheduleHELP {
            get {
                return ResourceManager.GetString("ScheduleHELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Class *.
        /// </summary>
        public static string SelClas {
            get {
                return ResourceManager.GetString("SelClas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Day *.
        /// </summary>
        public static string SelDay {
            get {
                return ResourceManager.GetString("SelDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Subject *.
        /// </summary>
        public static string SelSub {
            get {
                return ResourceManager.GetString("SelSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Time *.
        /// </summary>
        public static string SelTime {
            get {
                return ResourceManager.GetString("SelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Class Schedule Form.
        /// </summary>
        public static string UCSForm {
            get {
                return ResourceManager.GetString("UCSForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Class Schedule.
        /// </summary>
        public static string UpdateSched {
            get {
                return ResourceManager.GetString("UpdateSched", resourceCulture);
            }
        }
    }
}
