//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDiarySystem.Resources.Class.Create {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchoolDiarySystem.Resources.Class.Create.CreateTexts", typeof(CreateTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Create Form.
        /// </summary>
        public static string CCForm {
            get {
                return ResourceManager.GetString("CCForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Class.
        /// </summary>
        public static string CClass {
            get {
                return ResourceManager.GetString("CClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It enables us to create the class with its details:  teacher, class number, and room.
        ///
        ///If not all fields are filled in, the section:.
        /// </summary>
        public static string ClassHELP {
            get {
                return ResourceManager.GetString("ClassHELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also, if we try to add the same class, the part appears:.
        /// </summary>
        public static string ClassHELP_2 {
            get {
                return ResourceManager.GetString("ClassHELP_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Number *.
        /// </summary>
        public static string ClassNo {
            get {
                return ResourceManager.GetString("ClassNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Room *.
        /// </summary>
        public static string SelRoom {
            get {
                return ResourceManager.GetString("SelRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Teacher *.
        /// </summary>
        public static string SelTeach {
            get {
                return ResourceManager.GetString("SelTeach", resourceCulture);
            }
        }
    }
}
