//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDiarySystem.Resources.Student.Create {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchoolDiarySystem.Resources.Student.Create.CreateTexts", typeof(CreateTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Student.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Sudent Form.
        /// </summary>
        public static string CSForm {
            get {
                return ResourceManager.GetString("CSForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth *.
        /// </summary>
        public static string DoB {
            get {
                return ResourceManager.GetString("DoB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name *.
        /// </summary>
        public static string FirstN {
            get {
                return ResourceManager.GetString("FirstN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender *.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name *.
        /// </summary>
        public static string LastN {
            get {
                return ResourceManager.GetString("LastN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Student.
        /// </summary>
        public static string NewStud {
            get {
                return ResourceManager.GetString("NewStud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Class *.
        /// </summary>
        public static string SelClass {
            get {
                return ResourceManager.GetString("SelClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Parent *.
        /// </summary>
        public static string SelParent {
            get {
                return ResourceManager.GetString("SelParent", resourceCulture);
            }
        }
    }
}
